variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE/ganache:$CI_COMMIT_REF_SLUG
  CI_PATH: /apps/ci/crowdsale
  TAG: $CI_COMMIT_REF_SLUG

stages:
  - build
  #- test
  
before_script:
  - hostname && whoami && pwd
  - docker --version
  - docker-compose --version
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - echo "We will use docker tag TAG=$TAG and IMAGE_TAG=$IMAGE_TAG"
    - docker build -t $IMAGE_TAG .
    - docker images
    - docker push $IMAGE_TAG
  tags:
    - website-dev

# test:
#   stage: test
#   script:
#     - docker stop ganache || echo "Docker ganache wasn't running"
#     - docker pull $IMAGE_TAG
#     - docker run -d --rm -v $PWD:/dapp --name ganache $IMAGE_TAG -p 7545
#     - docker exec ganache truffle test --network development
#     - docker stop ganache || echo "We coud not stop docker ganache"
#   tags:
#     - website-dev